### ISSUE TITLE
"git reset --hard" triggers summary on all files

### ISSUE THREAD

**Issue by fjrdomingues** [fjrdomingues/autopilot#103]
**Problem**
If I do a `git reset --hard` on a repository, the application detects a gap fill on all files again, even if the content of the files is the same and the indexer starts indexing all files from scratch.

**Desired Outcome**
If the content of the files is the same, then the database shouldn't need to be updated for those files. This will allow databases to be copied and files to be moved without having to re-index the entire database again.

**Comment by hatkyinc2** [comment]
This should have been solved by using the file hashes
