### ISSUE TITLE
Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by Philomath88** [fjrdomingues/autopilot#114]
Task: move the sendEmail function into it's own script sendEmail.js in the modules folder
Summaries found in the database: 4
Tokens in Summaries: 402
(agent) getRelevantFiles
Calling GPT. Model:  gpt-3.5-turbo
Total tokens used: 4460 Total Cost: 0.01$
node:fs:601
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, open '/Users/maximiliandoelle/Projects/selling/N/A'
    at Object.openSync (node:fs:601:3)
    at Object.readFileSync (node:fs:469:35)
    at getFiles (/Users/maximiliandoelle/Projects/autopilot/modules/fsInput.js:107:27)
    at main (/Users/maximiliandoelle/Projects/autopilot/ui.js:215:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/maximiliandoelle/Projects/selling/N/A'
}

Node.js v18.16.0

**Comment by hatkyinc2** [comment]
You can look at what's going on using interactive mode `node -i`.

This sounds like gpt couldn't decide on what file you are referring to and made up `N/A` as it doesn't know.
The way the file selection work is by looking at the summaries it created for the files, you can look this up in the local sqlite DB.
I am working on improving stuff there, I'm happy to see this test case.

Also, I would note current code just does in-file updates, so it wouldn't refactor things to other files, create new files etc, that will be supported in some future point

**Comment by hatkyinc2** [comment]
The errors should now have proper messaging and ending.
Create new file type task was pinned off to a new ticket https://github.com/fjrdomingues/autopilot/issues/120
