### ISSUE TITLE
File too BIG

### ISSUE THREAD

**Issue by SphaeroX** [fjrdomingues/autopilot#115]
Problem
```
10:04: Updated summary for routes/recipe.js
Processing file: routes/user.js
File too BIG
```

Solution
Split bigger files

**Comment by SphaeroX** [comment]
Also got at the End this Error:
```

node:fs:601
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, open 'models/User.js'
    at Object.openSync (node:fs:601:3)
    at Object.writeFileSync (node:fs:2249:35)
    at updateFile (C:\Users\MGasc\OneDrive\Dokumente\autopilot\modules\fsOutput.js:56:8)
    at main (C:\Users\MGasc\OneDrive\Dokumente\autopilot\ui.js:226:7)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'models/User.js'
}
```

**Comment by hatkyinc2** [comment]
@SphaeroX for `File too BIG`, there is a constant `const maxTokenSingleFile = 3000;` https://github.com/fjrdomingues/autopilot/blob/10d9374f6e50df128abfac6859d6ea9522ad94bd/modules/summaries.js

you might get away with a different value.
Potentially this should be a formula taking into account the model used, I think gpt-3.5 had 4k max token, gpt-4 8k and some local models, which I hope we support in the future have only 2k.
This currently just looks at the file and we need some more tokens for the prompt and the actual output.

If you think it's worth it, can extract the value to the env as an easy change that might allow some extensions for some users, that's an easy change but of limited value.

Yes ultimately document splitting should help huge files, but needs to account for the missing logic parts, it's not just a text file you can cut anywhere, and you need to account for different file types... 

Do note this isn't a catastrophic error, it will just ignore that one file, assuming you have a project with many files. 

Is your project just one huge file generated by AI beforehand? or just seen this on a random file like package-lock?..

**Comment by hatkyinc2** [comment]
The const is not in the env file for easier testing
https://github.com/fjrdomingues/autopilot/blob/main/.env.template#L23
