### ISSUE TITLE
Context Overrun

### ISSUE THREAD

**Issue by jakenuts** [fjrdomingues/autopilot#132]
I pointed auto-pilot at a medium Typescript project, 73 files in total. It indexed them (love the switch to a db for this) and when I gave a pretty broad prompt like "review each file and add types where they aren't specified" it quickly hit an "This model's maximum context length is 4097 tokens. However, you requested 5831 tokens" error, understandable, I wait for a GPT-4 key on the edge of my seat. But when I narrowed the task to a single file, it continued to show the same context error. It seems like the summary of files is included in the context no matter the task, is that right?

Thanks

**Comment by hatkyinc2** [comment]
so we have find files that have 
input `MAX_TOKEN_COUNT_SUMMARIES_CHUNK` + 
output File list + (`OPENAI_MAX_TOKEN_REPLY`)

and the coder
input codefile +
output `OPENAI_MAX_TOKEN_REPLY` (so the idea that has to be at least as big as the file that is to be written, might also be multiple files in some tasks)


(yea... this needs work...)

**Comment by jakenuts** [comment]
Thanks so much, as the gods heard my cry and delivered a golden key this morning, any advice as to which agents would make best use of gpt-4 and which can doddle along in 3.5?

**Comment by hatkyinc2** [comment]
@jakenuts I don't have gpt-4, didn't experiment.
I believe @fjrdomingues is giving it to the advisor with the auto apply off which is what you can see the agent answering in issues.
