### ISSUE TITLE
Configure low temprature for GPT

### ISSUE THREAD

**Issue by hatkyinc2** [fjrdomingues/autopilot#16]
I think we are currently using the default, for most of the work here we probably want a low temperature to get more consistency and expected results and fewer hallucinations.

Basically, a high temperature is creative and a low one is closer to a deterministic, high-probability result.

**Comment by fjrdomingues** [comment]
That's a great point. Forgot to add that. What do you think about setting it to 0.2?

**Comment by hatkyinc2** [comment]
Will have to play with it at some point and learn from experience, I would try 0, to see if it works well as close to deterministic.
Especially if we try to loop improvements later... 
But adding it in the code and putting the value in configuration is a good way to open the door, and let the user be able to play with it.

**Comment by hatkyinc2** [comment]
https://github.com/fjrdomingues/autopilot/pull/45
This PR should resolved this ticket
