### ISSUE TITLE
When cloning the project the indexer finds a gap on all files

### ISSUE THREAD

**Issue by fjrdomingues** [fjrdomingues/autopilot#162]
**Background story explaining the current situation:**
The repo has a committed database for the existing files, even so, when using the repo from a clean cloning, the indexer thinks that there are no matching files in the DB.

**Desired new situation:**
When I clone the repo, the existing database in the repository works for at least the majority of the files, so we don't have to reindex and create summaries for all files again.

**Implementation details:**
I don't know what is causing this. Maybe different machines or OS are creating different hashes for files? - Just a guess

<img width="568" alt="image" src="https://user-images.githubusercontent.com/23214157/235379719-05632771-2d65-4106-b48b-7b1da76d1309.png">

**Comment by fjrdomingues** [comment]
Uploading "hashing.js" file to https://emn178.github.io/online-tools/sha256_checksum.html gives me the following hash: `a77e23a043ff4479ad8251cdeb0106ba5270406e21f160d1681457787b61a3bd`. Different from the hash that is in the current db on the repo, which was committed less than 24 hours ago.

**Comment by hatkyinc2** [comment]
It's possibly the difference in OS with newlines.

>The Mac, by default, uses a single carriage return ( <CR> ), represented as \r . Unix, on the other hand, uses a single linefeed ( <LF> ), \n . Windows goes one step further and uses both, creating a ( <CRLF> ) combination, \r\n .

git usually confirms to that on checkout, fetch and stuff

So this slight difference would translate to a difference in hash values.

we might want to change the files strings before hashing to get this consistent across OSs
