### ISSUE TITLE
Error when running a task using node ui -t "TEST"

### ISSUE THREAD

**Issue by lanalex** [fjrdomingues/autopilot#165]
**Describe the issue**
Users/alexlan/Code/autopilot/node_modules/langchain/dist/output_parsers/structured.cjs:74
            throw new index_js_1.OutputParserException(`Failed to parse. Text: ${text}. Error: ${e}`);
                  ^

OutputParserException [Error]: Failed to parse. Text: ```json
{
	"thoughts": {
		"text": "Refactor the code to improve readability and maintainability. Add comments to explain the purpose of each function and class. Use more descriptive variable names. Use consistent formatting throughout the code.",

**Version details**
AutoPilot version tested: (`git rev-parse HEAD`)
8d1ea5677f51b0e961d613bd900fa824d7eb7c0f

Node version: (`node --version`)
v20.0.0

**Task input**
What was the task text provided?

**Logs**
What did you get on screen:

The content of the last file under the `logs` directory:

**Expected behavior**

**Additional context**

**Comment by hatkyinc2** [comment]
Big task 😅 
This error is when the model is giving a bad answer, the returned format is incorrect, we have this task to try to mitigate that. (there is already code trying to fix bad responses but 🤷 , could probably also catch the issue and put a better message to the user `your agent was bad today, try again`)
https://github.com/fjrdomingues/autopilot/issues/160
