### ISSUE TITLE
Idea: Add GitHub repo support

### ISSUE THREAD

**Issue by ryanmac** [fjrdomingues/autopilot#2]
This is a fantastic tool. In addition to local repos, I'd love to see support for remote repos. Ideally, multiple. In this way, autopilot could build context around one or more local or remote repos.

**Comment by hatkyinc2** [comment]
Are you just wishing for a script that includes `git clone`?
or is it about package dependency? (you can change the include/exclude lists)
or just multiple directories in general?

**Comment by siwatanejo** [comment]
If this is added, it could lead the way to GPTx to provide PRs automatically from github issues, similar to what this achieves: https://github.com/irgolic/AutoPR/

**Comment by fjrdomingues** [comment]
An easy way is to do it for OSS repos. Allowing autopilot to get the code and issues from the repo and suggest PRs. Best way to prove the concept and quality of autopilot. Getting some PRs approved would be a major step 🚀
This way we can avoid the complexity of integrating with git providers and focus on the quality of the code that it can generate.

**Comment by hatkyinc2** [comment]
I have another project I can reuse scripts from which just do the loop of something like
```
(find/list projects)
github fork
git clone
call something - autopilot
git commit
git push 
github open pull request
```
IIRC there is a cli tool just named gh as github cli that allows for a lot of this easily

But anyway while it's nice I think that could be logically separated and probably technically separate from autopilot itself.
maybe if we have like a codespace/project we can put both repos under the same area

I just am trying to split the logical parts which seem a bit unrelated.
So while the git tool would be using autopilot I don't think it needs to be embedded into autopilot itself.

So the autopilot scope I think shouldn't include github stuff, maybe some git to diff/apply, but honestly even that is better not to be core here.


thoughts?

**Comment by hatkyinc2** [comment]
There is some work already in progress for this, due this ticket is not very detailed
https://github.com/fjrdomingues/autopilot/pull/91
