### ISSUE TITLE
Something in the cost calculation is totally broken

### ISSUE THREAD

**Issue by hatkyinc2** [fjrdomingues/autopilot#3]
Calling GPT. Model:  gpt-3.5-turbo
Total tokens used: 15814 Total Cost: 0.80$

15814 * 0.002 / 1000 = 0.031628$

Oh I think you're adding the costs, while also adding the tokens and recalculating the costs

```
    totalTokensUsed += usage.total_tokens; // increment total tokens used
    cost += calculateTokensCost(GPTModel, promptTokens, completionTokens, totalTokensUsed)
```

So you add the tokens across the process
but than the cost is already the total cost from calculateTokensCost
but you also add the last cost to the current cost
should choose either, not both, either add the costs but don't use the totalTokens across the project, just the current file
or don't add cost to cost, just recalculate based on totalTokens that has already been aggregated 

(btw did you look at langchain as a possible framework for this?..)

**Comment by fjrdomingues** [comment]
ahah man, loved your comment. Seems that you are correct. It also means that I haven't been spending as much as I thought, great :D! Going to merge your PR.

Langchain would probably be useful but I haven't explored how tho. Also auto-gpt
Any thoughts on that?

**Comment by hatkyinc2** [comment]
I've just started playing with it all

your idea about asking it to explain the file and saving it is interesting
in langchain they load documents, tokenize them and save to a special type of DB for tokes (IDK if that's good for code or not, I assumed yes, but maybe I'd find it wrong?)
So my simple project that split across many files (front end) is already too big for the current system here.

So I wanted it to actually change code as I do now directly with chatGPT or playground...

The next step in langchain in my thinking is also let it run against a compiler and loop back on errors to fix. or just improvement loops...

another interesting item would be to try gpt4all as local runs without exposing the code to a vendor

...
