### ISSUE TITLE
Using node ui.js it seems to work on the autopilot subdir rather than the parent dir where my code is?

### ISSUE THREAD

**Issue by Charuru** [fjrdomingues/autopilot#30]
The CODE_DIR=../. is configured, and the summarization worked just running the tasks didn't.

**Comment by hatkyinc2** [comment]
Should be fixed in https://github.com/fjrdomingues/autopilot/pull/27

If you want for now you can check my fork
https://github.com/hatkyinc2/autopilot

**Comment by fjrdomingues** [comment]
@hatkyinc2 invited you as a collaborator to the repo (I'm a noob in some of this stuff so let me know if it doesn't work)

**Comment by Charuru** [comment]
Thanks I did just fix it myself, but since #27 is merged I think this could be closed.
