### ISSUE TITLE
Move all the prompts to a single location

### ISSUE THREAD

**Issue by hatkyinc2** [fjrdomingues/autopilot#33]
I think the prompts would be a sort of config that people would likely edit... as we would be experimenting in getting this working better

**Comment by fjrdomingues** [comment]
At the moment I'm finding the prompt very related to the agent itself, its purpose and its output. So yes, but on the agent level and not on the prompt level. A config for agents. 
Agree?

**Comment by hatkyinc2** [comment]
This might be too fwd thinking, it would be clearer after stuff stabilizes a little.
It might be just a part of a prompt, so landchain talks about prompt templates
So where we have 
```
File:
{file}
Instructions: "our long prompt"
Expected output format: "some instructions about expected JSON
```

Then the thing about the prompt I think should be easily available across all agents is the instructions portion

"act like junior/senior dev and ...."

Maybe later, but I think this is the text both developers on this and advanced users would change the most.
And maybe advanced users should review and align to what they expect.

So for the coder, you can add personal coding styles. things they find important and are specific to the group working with this.
in the concept of there is many ways to achieve the same thing.

**Comment by hatkyinc2** [comment]
Currently, we at least have all the prompts under /agents/
I think working on this I learned this might not be viable as a generic approach as each is tightly coupled to inputs and outputs.
Small changes are likely to break the tool.
Maybe we might offer specific prompt injections which would make sense in the future, possibly it would just be some extra text you want for the code, for example 'follow X standard' 
But I don't think we are the point to understand what this future task is
closing for now.
