### ISSUE TITLE
Discoussion: Next steps after results

### ISSUE THREAD

**Issue by hatkyinc2** [fjrdomingues/autopilot#34]
I guess we are still in kinda discovery stage...

I'm thinking after a code patch is suggested, what is next? currently, it's just pointing to a result file.
What I think would be nice to have is a chat continuation where the solution is lets say printed to screen and than the user can either:
1. Apply the change.
2. Ask for changes to the current solution. (renaming function/var is an easy example, no need to feed files again, just the current suggestion)
3. Start over (new task text, basically loop to the start).
(loopback)
so kinda continues mode

maybe with `--felling-luky` which is a YOLO - just apply change automatically

**Comment by fjrdomingues** [comment]
Loving your thinking!
That mechanism that you described sounds very similar to how Pull Requests work. autopilot could apply changes, open a PR and wait for feedback on the PR to iterate. More work but may be worth the investment to already integrate with a standard interface and workflow.

**Comment by hatkyinc2** [comment]
we now have an interactive mode that askers the interaction part
Auto apply is still in progress, need to refactor the previous attempt, and see if it's any better or at least keep the suggestions as just extra options for now...

**Comment by hatkyinc2** [comment]
Auto applier is in progress https://github.com/fjrdomingues/autopilot/issues/74

I'm kind of happy to close this for now. 
Further thoughts about were this is going were discussed and we can park this for now I feel.
