### ISSUE TITLE
Incorrect File Extensions Recommended by Autopilot

### ISSUE THREAD

**Issue by lmsutools** [fjrdomingues/autopilot#42]
Hello, thanks for such a great project. I see it has big future!
ISSUE:
All of my project files are saved with the .js extension, but Autopilot is suggesting that I use other file extensions such as .php and .py. This is causing confusion and may lead to errors in my code.

I have noticed that the following files have been recommended with the wrong file extensions:

CONSOLE LOG:
Relevant Files are:  [
  {
    path: 'licenses_table.php',
    reason: 'This file likely handles the creation and activation of licenses, so it will need to be updated to include the new columns.'
  },
  {
    path: 'products_table.php',
    reason: 'This file likely handles the creation and activation of products, so it will need to be updated to include the new columns.'
  },
  {
    path: 'retrieve_license_info.php',
    reason: 'This file likely retrieves license information, so it may need to be updated to include the new columns.'
  },
  {
    path: 'update_license_info.php',
    reason: 'This file likely updates license information, so it may need to be updated to include the new columns.'
  }
]
node:fs:594
  handleErrorFromBinding(ctx);
  
  It would be helpful if Autopilot could recommend file extensions that match the current file types being used in my project. In addition, I received the following error message in relation to this issue:

node:fs:594 handleErrorFromBinding(ctx);
<img width="427" alt="image" src="https://user-images.githubusercontent.com/104270019/230696229-3a3236e9-e89e-4725-8208-935e7aa6a982.png">

<img width="867" alt="image" src="https://user-images.githubusercontent.com/104270019/230696241-249c6ddc-98bf-427f-bd63-e24ad93f640f.png">

And also, this strage behaviour.
<img width="137" alt="image" src="https://user-images.githubusercontent.com/104270019/230696254-4c3c3953-c835-4b53-8d57-4f9023d63c07.png">

**Comment by hatkyinc2** [comment]
This last part is actually the answer to everything.
It's hallucinating file names as it doesn't have any content.

Have you run `node createSummaryOfFiles.js --all`?

**Comment by hatkyinc2** [comment]
Getting the summaries and showing nothing is the core issue, it didn't load the index files.

Make sure you try the latest version, we had an issue like that before https://github.com/fjrdomingues/autopilot/commit/74ddbc8d9e959adcaa298b3226e0157fbc83a84f

if it still has this issue, you can help us find the issue, this project is really fresh and unstable for now

**Comment by hatkyinc2** [comment]
https://github.com/fjrdomingues/autopilot/issues/26

**Comment by fjrdomingues** [comment]
@lmsutools Let us know if you made it work. Finding summary files is essential for autopilot to function properly.

**Comment by lmsutools** [comment]
> @lmsutools Let us know if you made it work. Finding summary files is essential for autopilot to function properly.
> 
> @hatkyinc2 we should stop the program with no summary files found. No point in continuing without context of the repo.

Problem persists. Maybe is because I'm on windows and putting the path in windows format?
![image](https://user-images.githubusercontent.com/104270019/230751749-c0d6cd61-ff2a-4df5-bd79-f5238982bde7.png)

My env file dir code is:
CODE_DIR=C:\GitTests\Lamassu-Licensing-Server\

**Comment by lmsutools** [comment]
I also used relative path as autopilot folder is on the same path level as my project, but still the same problem.
CODE_DIR=../Lamassu-Licensing-Server/
