### ISSUE TITLE
No files found [Windows 11]

### ISSUE THREAD

**Issue by lmsutools** [fjrdomingues/autopilot#48]
## .ai.txt files create sucessfully

<img width="434" alt="image" src="https://user-images.githubusercontent.com/104270019/230752132-04851244-4085-429a-afdd-462333f59184.png">

## No matching files found. Try running `node createSummaryOfFiles` first.
<img width="580" alt="image" src="https://user-images.githubusercontent.com/104270019/230752139-e53542e8-5ed4-429b-8b75-93dbce57b83c.png">

I'm on Windows.
In the .env file, I have tried 
- relative paths:
 CODE_DIR=../Lamassu-Licensing-Server/
- Normal windows filepath:
CODE_DIR=C:\GitTests\Lamassu-Licensing-Server\
- And forward slash 
- CODE_DIR=C:/GitTests/Lamassu-Licensing-Server/

**Comment by hatkyinc2** [comment]
I'd encourage you to debug this yourself,
It's just that one line that read the summary files
```
files = await fg(path.posix.join(process.env.CODE_DIR, '**/*.ai.txt'), { ignore: ignorePattern });
```
https://github.com/fjrdomingues/autopilot/blob/Edge/modules/summaries.js#L33

Or basically try to run
`node`
```
const fg = require('fast-glob');

const ignorePattern = ['node_modules/**/*'];
CODE_DIR=C:/GitTests/Lamassu-Licensing-Server/
await fg(path.posix.join(CODE_DIR, '**/*.ai.txt'), { ignore: ignorePattern });
```

**Comment by lmsutools** [comment]
the last update fixed it, thanks
