### ISSUE TITLE
Config: move createSummaryOfFiles model selection to config

### ISSUE THREAD

**Issue by hatkyinc2** [fjrdomingues/autopilot#8]

**Comment by fjrdomingues** [comment]
Hi, @hatkyinc2 what do you mean by "module" in this context?

**Comment by hatkyinc2** [comment]
Sorry should have been `model`

Already done in that linked merged PR, closing.

The generic idea here and in https://github.com/fjrdomingues/autopilot/issues/9 is to remove hardcoded stuff and allow for more flexibility, some of the reasons:
* Not everyone has access to all the models (gpt4)
* Not all models cost the same.
* Not all models produce the same results and people may want to try others.
* openAI will keep changing models. (gpt5 is in training for a while already rumors say)
* Going forward I'm sure flexibility to replace OpenAI with other modules would be used by people even if we are not implementing it yet, it's a good path. Personally, I'd want to try gpt4all at some point. A sample list from langchain https://python.langchain.com/en/latest/modules/models/llms/integrations.html
