### ISSUE TITLE
error

### ISSUE THREAD

**Issue by analogpvt** [fjrdomingues/autopilot#96]
node:fs:601
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, open 'app.js'
    at Object.openSync (node:fs:601:3)
    at Object.readFileSync (node:fs:469:35)
    at getFiles (/root/folder/autopilot/modules/summaries.js:62:28)
    at main (/root/folder/autopilot/ui.js:137:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: 'app.js'
}

**Comment by r1di** [comment]
I'm having the same issue

**Comment by fjrdomingues** [comment]
Was getting a similar problem. The getFiles function is not taking into account the CODE_DIR env var (modules\summaries.js:62:28)

I fixed that in #97 you can try that branch or wait for it to be merged

**Comment by r1di** [comment]
Thanks, that seems to be the problem. But there still seems to be some problems in general, it looks for the file in wrong directories.

**Comment by hatkyinc2** [comment]
The summaries have just had a major re-work including a lot of testing with the CODE_DIR, relative vs absolute, *nix vs windows
The latest work is currently under https://github.com/fjrdomingues/autopilot/pull/98

@analogpvt @r1di 
if you guys want to try it out.
Notice the doc changes as well, it replaces all the `.ai.txt` files with a local DB, no more separate indexer, default is just using `node ui -t "TASK"` and the summaries should be ok by themselves...

Apologies for the low testing on some versions, we do need help introducing some automated testing if interested.
Hopefully, after some of these major reworks, we would have more stability.

**Comment by hatkyinc2** [comment]
Please try the latest version a lot of this has been reworked
